### ISSUE TITLE
When creating a user, the library makes infinite requests to search if the user exists

### ISSUE THREAD

**Issue by dodancs** [marcospereirampj/python-keycloak#186]
Hi.

I am currently using the version 0.24.0 of the library. When I make a call to the create_user function, the internal function [__fetch_all()](https://github.com/marcospereirampj/python-keycloak/blob/ff4669979973c3744dfcfb415840b44dcaf88a5c/keycloak/keycloak_admin.py#L201) does not stop, and infinetely tries to get all search results, because Keycloak always returns the same array of users.

I think, that the API specification changed for Keycloak, and therefore this is now unusable.

I am using the jboss/keycloak docker image v12.0.4 for the Keycloak server.

Anyone else experienced this issue?

**Comment by double-a** [comment]
Hi  @dodancs, I did not find any differences in the API. Maybe you can give me a hint (e.g. https://www.keycloak.org/docs-api/12.0/rest-api/index.html).

Create_user only calls fetch_all() if called with `exists_ok = True`. Then it searches via `get_user_id()` for the provided username (which could match hundreds of users, e.g. username="e"). Those users are retrieved and filtered again for the exact matches which might take some time but should not cause a crash.

How many users do you have? What username are you searching for?

**Proposed enhancement**: search using "exact":"true" should limit the number of returned results on the server side, i.e. in `keycloak_admin.py` you could change `get_users_id()` to
`        users = self.get_users(query={"search": username, "exact":True})
`
Note that search via `exact` is only supported since keycloak 11.0 thus the final check should be kept for backward compatibility.

**Comment by dodancs** [comment]
Hi.

So I've found the issue. It wasn't related to the keycloak python library. It was an issue with the HTTPS proxy which did not forward the request arguments so keycloak always returned all users.

Sorry for wasting your time, but thank you for providing some advice!

Have a nice day!
