### ISSUE TITLE
async version

### ISSUE THREAD

**Issue by Stasyanz** [marcospereirampj/python-keycloak#337]
any info about async version of the package?

**Comment by ryshoooo** [comment]
Hi @Stasyanz 

Currently, we support neither any async version nor async functionality. My guess is that it'd take quite a significant amount of work to have this feature. And for that, I'd like to see and hear how many more are interested in this.

You can try patching `requests` with `requests-async` upon import, but I wouldn't really raise my hopes up too much. There are many places where we expect a response instead of a future response, but it could work for some methods.

**Comment by obi-081** [comment]
Hi !
I'm interested too, it would be a very cool feature.
You may have a look at httpx if you want to do that, I think it is the best option.
https://www.python-httpx.org/
This would allow our WebServers to continue to serve requests when waiting for KeyCloak Response.

**Comment by alexisgaziello** [comment]
It looks like there is an unmaintained forked repo that attempts to add the async functionality:

https://github.com/jegork/python-keycloak

**Comment by Jdsleppy** [comment]
I have a handwritten async Keycloak client that I'm considering bundling up into a library for reuse.  I would prefer to put that effort into adding async to this library if the maintainers are interested in reviewing, merging, and releasing that work.

I would end up duplicating the existing test suite functions to make async versions of each test that could run against the same Keycloak instance.  As other commenters have suggested, I would consider moving from `requests` to `httpx` which has a nearly perfectly `requests`-compatible sync API, so hopefully most of the changes to existing code would just be replacing `requests` with `httpx`.  If that ends up being too difficult, then the new code could just use `httpx` and leave the sync version using `requests`.

Please let me know if you would be interested in incorporating changes like this into the library if I forked and developed it.  @ryshoooo @marcospereirampj

**Comment by ryshoooo** [comment]
Hi @Jdsleppy 

I'm definitely interested in having async functionality as a native part of the library. So definitely feel free to create a PR :) I promise to find the time for review and merge.

**Comment by drikster80** [comment]
> I have a handwritten async Keycloak client that I'm considering bundling up into a library for reuse. I would prefer to put that effort into adding async to this library if the maintainers are interested in reviewing, merging, and releasing that work.
> 
> I would end up duplicating the existing test suite functions to make async versions of each test that could run against the same Keycloak instance. As other commenters have suggested, I would consider moving from `requests` to `httpx` which has a nearly perfectly `requests`-compatible sync API, so hopefully most of the changes to existing code would just be replacing `requests` with `httpx`. If that ends up being too difficult, then the new code could just use `httpx` and leave the sync version using `requests`.
> 
> Please let me know if you would be interested in incorporating changes like this into the library if I forked and developed it. @ryshoooo @marcospereirampj

@Jdsleppy, I sent you a message on LinkedIn. I'd be interested in sponsoring you for integration of async functions into this library.

**Comment by derekpy3ai** [comment]
Hi @ryshoooo , I am working on this feature.

Approach:
I am working on implementing separate classes in a submodule for async with all the async functions and httpx client.  This way it won't affect the already existing functionality.

**Comment by derekpy3ai** [comment]
Hi @ryshoooo, I am almost done with my implementation.

Solution Branch:
https://github.com/pyaiman/python-keycloak/tree/async_feature

Approach:
1. I have introduced a new httpx client in the connection class alongside the original requests client. So that the users do not have to initialize a different connection to use async functions.
2. Created separate async methods in each class replicating the original methods but using the httpx client instead of requests.Client(). Original methods are untouched so this will not effect the original functionality
3. Created new async test cases using pytest-asyncio to cover the async functions.
