### ISSUE TITLE
create_client: client name is neither mandatory nor unique per realm.  clientId does not need to be a uuid.

### ISSUE THREAD

**Issue by jputney** [marcospereirampj/python-keycloak#351]
create_client with skip_exists=True throws an exception if name is undefined on the payload.  

  File "<...>/lib/python3.9/site-packages/keycloak/keycloak_admin.py", line 1268, in create_client
    client_id = self.get_client_id(client_name=payload["name"])
KeyError: 'name'

In get_client_id tries to lookup clientId by name, but name is non-unique.  It also says clientId is a uuid as string, but it is an arbitrary string.

**Comment by jputney** [comment]
I can volunteer to submit a patch if its agreed that the current behavior is incorrect.

**Comment by jputney** [comment]
I think the behavior most consistent with the data-model and web console would be:

1) client name would be treated as data, not an identifier.  So, clients with duplicate names can be created in the same realm.
2) if clientId is not specified, a new instance will always be created and keycloak will generate and return a uuid as its clientId
3) if clientId is specified, and skip_exists = true, then it will check for the client already existing and return without doing anything if it finds a matching clientid.

**Comment by ryshoooo** [comment]
> I think the behavior most consistent with the data-model and web console would be:
> 
> 1. client name would be treated as data, not an identifier.  So, clients with duplicate names can be created in the same realm.
> 2. if clientId is not specified, a new instance will always be created and keycloak will generate and return a uuid as its clientId
> 3. if clientId is specified, and skip_exists = true, then it will check for the client already existing and return without doing anything if it finds a matching clientid.

Hi @jputney 
The behavior described here sounds sane and overall quite reasonable. I think part of this patch the method `get_client_id` should be reconsidered as well https://github.com/marcospereirampj/python-keycloak/blob/b08137c4f9ae17d7fbb683e55743dcd94f91ec4d/src/keycloak/keycloak_admin.py#L1056. Since it checks the match on both client name and client id under the suspiciously named variable `client_name`. Since names are not unique, the check should only be on client id. This way the patch can be very easy to do.

The 2. and 3. are not necessary as Keycloak REST API demands clientId to be specified upon create client request, so client id has to be specified in the payload. I made the wrong assumption that the `name` was required as well, but I can see it's not now :) So really just patching the `get_client_id` method to only do lookup on clientId and renaming `name` to `clientId` in the `create_client` method should do it.

If you wish to, feel free to have a go at this :)
