### ISSUE TITLE
client_secret_key is not being validated?

### ISSUE THREAD

**Issue by sergiocwork** [marcospereirampj/python-keycloak#489]
I am using a keycloak `confidential` client. I have generated a key for the client. Using the client secret, I connect to the client via `keycloak_openid = KeycloakOpenID(
    server_url="https://keycloak.me:8443/auth/",
    client_id="backend",
    client_secret_key="KbearRbXZdLbgJXtbfqVp5g1JE3DlQjZ",
    realm_name="turbo",
    verify=True,
)`

If I enter the wrong client_secret_key, I get no issues. Is the client_secret_key not validated? Why can I still use userinfo or decode_token when I am no longer initializing with the correct client secret?

**Comment by ahmedsmaali5** [comment]
Can you give us your keycloak exact version?

**Comment by sergiocwork** [comment]
Using Keycloak 18.0.

**Comment by ryshoooo** [comment]
AFAIK, client_secret is used for granting of tokens, i.e. in for the `token` method of the `KeycloakOpenID` class. The moment you have a valid access/refresh token from the client, the client secret is not relevant anymore. Userinfo endpoint just uses the access token to give the user-info, as the access token holds the client data. Decode token does not require any client, you can actually decode any JWT token without verification at any time without any credentials. So to me this works as expected, the only surprise would be if the `token` method worked without client secret as well, but that should be then pointing to the `keycloak` project rather than this python SDK.

**Comment by sergioc32** [comment]
Sounds like I don't fully understand oidc authentication. I was trying to
use two clients in keycloak, a public client on my frontend that would
authenticate and pass the token to the backend, which is a private client
with a secret, that would mainly verify the token. From your response, that
isn't the purpose of the  token  or decode_token method and it's really
decoding a jwt which does not require a client secret. Thanks for the
response and sorry for the confusion.

**Comment by codespearhead** [comment]
Should this issue be closed then?

**Comment by sergiocwork** [comment]
Yes, you can close the ticket. I'm still not sure why the client_secret_key is not used but seems like that is just my issue.

Thanks,
Sergio Cardoso
________________________________
