### ISSUE TITLE
Adding user to a group

### ISSUE THREAD

**Issue by IanSzejer** [marcospereirampj/python-keycloak#561]
Hello,

Im using the keycloak image: quay.io/keycloak/keycloak:23.0.1
I tried to update a user and him to a group and it didnt gave an error but it did nothing

Example:  kc_admin.update_user(user_id=user_id_keycloak, payload={'groups': ['regular_user']})

Then i did the exact same thing when creating the user and it worked. So definitly is the update user that is failing.

**Comment by ryshoooo** [comment]
Hi @IanSzejer

As this library just delegates the action to the Keycloak's Admin REST API and does not perform any special handling of the specified payload (at least in the `update_user` method), I'd direct this report to the upstream project instead https://github.com/keycloak/keycloak. From your description, it sounds like a Keycloak issue rather than a python-keycloak issue.

**Comment by IanSzejer** [comment]
Yes, i just found and realize is not a issue from the library rather an issue from the endpoint update handling. 
Thanks!!
